version: "3.8"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo_db:app_db

  mongo_db:
    image: "mongo:4.4.3"
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017


  mongo-express:
    image: mongo-express
    container_name: mong-express
    restart: always
    ports:
      - 8081:8081